// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pizza_Data.Models;

namespace Pizza_Data.Migrations
{
    [DbContext(typeof(OOPContext))]
    partial class OOPContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pizza_Data.Models.CompletedOrders", b =>
                {
                    b.Property<int>("OrderId")
                        .HasColumnName("orderId")
                        .HasColumnType("int");

                    b.HasKey("OrderId")
                        .HasName("PK__Complete__0809335D1A05C904");

                    b.ToTable("CompletedOrders");
                });

            modelBuilder.Entity("Pizza_Data.Models.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("orderId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlacedAt")
                        .IsRequired()
                        .HasColumnName("placedAt")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnName("storeName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("TotalCharges")
                        .HasColumnName("totalCharges")
                        .HasColumnType("money");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__0809335D02FEB31D");

                    b.HasIndex("StoreName");

                    b.HasIndex("Username");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Pizza_Data.Models.Pizzas", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("pizzaId")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Crust")
                        .IsRequired()
                        .HasColumnName("crust")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("PizzaType")
                        .IsRequired()
                        .HasColumnName("pizzaType")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<decimal>("Price")
                        .HasColumnName("price")
                        .HasColumnType("money");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnName("size")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("PizzaId")
                        .HasName("PK__Pizzas__4D4C90EF095EE0CB");

                    b.HasIndex("Username");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("Pizza_Data.Models.Store", b =>
                {
                    b.Property<string>("StoreName")
                        .HasColumnName("storeName")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnName("venue")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("StoreName")
                        .HasName("PK__Store__0E3E451C199CC4C7");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("Pizza_Data.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("Username")
                        .HasName("PK___User__F3DBC5733C3A50F6");

                    b.ToTable("_User");
                });

            modelBuilder.Entity("Pizza_Data.Models.CompletedOrders", b =>
                {
                    b.HasOne("Pizza_Data.Models.Orders", "Order")
                        .WithOne("CompletedOrders")
                        .HasForeignKey("Pizza_Data.Models.CompletedOrders", "OrderId")
                        .HasConstraintName("FK__Completed__order__6E01572D")
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza_Data.Models.Orders", b =>
                {
                    b.HasOne("Pizza_Data.Models.Store", "StoreNameNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("StoreName")
                        .HasConstraintName("FK__Orders__storeNam__6A30C649")
                        .IsRequired();

                    b.HasOne("Pizza_Data.Models.User", "UsernameNavigation")
                        .WithMany("Orders")
                        .HasForeignKey("Username")
                        .HasConstraintName("FK__Orders__username__6B24EA82")
                        .IsRequired();
                });

            modelBuilder.Entity("Pizza_Data.Models.Pizzas", b =>
                {
                    b.HasOne("Pizza_Data.Models.User", "UsernameNavigation")
                        .WithMany("Pizzas")
                        .HasForeignKey("Username")
                        .HasConstraintName("FK__Pizzas__username__49C3F6B7")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
